export { createManager, manager, SkillsManager } from './core/manager';
export type { ManagerOptions } from './core/manager';
export type {
    FileHashEntry,
    LockData,
    LockSourceMeta,
    ManagedSkillEntry,
    ManagerEvent,
    ManagerErrorResult,
    ManagerHeader,
    ManagerTemplatesCreatedResult,
    ManifestData,
    ManifestPublishConfig,
    ManifestSourceEntry,
    PublishCommandOptions,
    PublishCommandResult,
    PublishCompletedResult,
    ResolvedSourceMeta,
    SharedSyncError,
    SharedSyncResult,
    SkillEntry,
    SkillTreeHash,
    SyncAddFailedResult,
    SyncCancelledResult,
    SyncCommandOptions,
    SyncCommandResult,
    SyncCompletedResult,
    SyncConfirmationRequest,
    SyncInstallResult,
    SyncPlan,
    SyncPreflight,
    SyncPreflightConflict,
    SyncRemovalSummary,
    SyncSharedFailedResult,
} from './core/types';
